### ISSUE TITLE
Create user uploaded dataset component (First Phase)

### ISSUE THREAD

**Issue by augusto-proano** [Graphitti/graphiti#2]
![screen shot 2018-06-20 at 12 24 15 pm](https://user-images.githubusercontent.com/29712763/41671511-53c70f60-7485-11e8-9160-35f0f4388b04.png)

-Must be able to read CSV file in order to render the user input file in columns and rows.

**Comment by Sampandu** [comment]
some npm package, like react-dropzone, might could be used directly, without creating from scratch.

**Comment by Sampandu** [comment]
npm react-table package could display the data in table form
