### ISSUE TITLE
Add customize rows into users dataset component

### ISSUE THREAD

**Issue by augusto-proano** [Graphitti/graphiti#3]
![screen shot 2018-06-20 at 12 24 15 pm](https://user-images.githubusercontent.com/29712763/41671883-73a7f4d8-7486-11e8-914d-f03e368139bc.png)

- Must be able to show dataset with a specific amount of rows, also should be able to show the next pages
-As a user I should be able to chose how many rows I want to display

**Comment by Sampandu** [comment]
the react-table package has this built-in feature already
