### ISSUE TITLE
Researching best option for Graph input files

### ISSUE THREAD

**Issue by andressantos94** [Graphitti/graphiti#4]
Graphs: .csv is the only and better option as input file? How can we render .csv files into web tables just in front end? 
Important: Don't forget that we need to persist data later. Can we fill up database with .csv or other files?

**Comment by Sampandu** [comment]
'react-dropzone' is a npm package which might be used directly, without creating from scratch.  This is a tutorial article : https://medium.com/technoetics/handling-file-upload-in-reactjs-b9b95068f6b
