### ISSUE TITLE
Researching libraries for rendering Graphs

### ISSUE THREAD

**Issue by andressantos94** [Graphitti/graphiti#5]
Is d3.js a solution for rendering graphs? How it works?
What about react-chart.js? How it works? 
another option?? How it works?

**Comment by Sampandu** [comment]
ReCharts is a lightweight chart library built with React and based on the D3 charting library. 
The example of the link: http://recharts.org/#/en-US/examples

**Comment by augusto-proano** [comment]
Simple yet flexible JavaScript charting for designers & developers
http://www.chartjs.org/samples/latest/charts/line/basic.html
